// Fallback data parsed from Google Sheet
const villaData = [
  {
    "house_name": "About A Beach Pool Villa",
    "price_monday": 8000,
    "max_people_monday": 12,
    "price_tuesday": 8000,
    "max_people_tuesday": 12,
    "price_wednesday": 8000,
    "max_people_wednesday": 12,
    "price_thursday": 8000,
    "max_people_thursday": 12,
    "price_friday": 9000,
    "max_people_friday": 12,
    "price_saturday": 15000,
    "max_people_saturday": 12,
    "price_sunday": 8000,
    "max_people_sunday": 12,
    "far_sea": 100,
    "bed_room": 4,
    "toilet": 5,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 666.67,
    "avg_price_per_person_tuesday": 666.67,
    "avg_price_per_person_wednesday": 666.67,
    "avg_price_per_person_thursday": 666.67,
    "avg_price_per_person_friday": 750,
    "avg_price_per_person_saturday": 1250,
    "avg_price_per_person_sunday": 666.67
  },
  {
    "house_name": "Alisa pool villa",
    "price_monday": 6000,
    "max_people_monday": 14,
    "price_tuesday": 6000,
    "max_people_tuesday": 14,
    "price_wednesday": 6000,
    "max_people_wednesday": 14,
    "price_thursday": 6000,
    "max_people_thursday": 14,
    "price_friday": 7000,
    "max_people_friday": 14,
    "price_saturday": 14000,
    "max_people_saturday": 14,
    "price_sunday": 6000,
    "max_people_sunday": 14,
    "far_sea": 3000,
    "bed_room": 4,
    "toilet": 4,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 428.57,
    "avg_price_per_person_tuesday": 428.57,
    "avg_price_per_person_wednesday": 428.57,
    "avg_price_per_person_thursday": 428.57,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 428.57
  },
  {
    "house_name": "Another Hour Pool Villa",
    "price_monday": 8000,
    "max_people_monday": 15,
    "price_tuesday": 8000,
    "max_people_tuesday": 15,
    "price_wednesday": 8000,
    "max_people_wednesday": 15,
    "price_thursday": 8000,
    "max_people_thursday": 15,
    "price_friday": 9000,
    "max_people_friday": 15,
    "price_saturday": 15000,
    "max_people_saturday": 15,
    "price_sunday": 8000,
    "max_people_sunday": 15,
    "far_sea": 5500,
    "bed_room": 6,
    "toilet": 5,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 533.33,
    "avg_price_per_person_tuesday": 533.33,
    "avg_price_per_person_wednesday": 533.33,
    "avg_price_per_person_thursday": 533.33,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 533.33
  },
  {
    "house_name": "Ashy pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 4000,
    "max_people_friday": 10,
    "price_saturday": 9000,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 5800,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 400,
    "avg_price_per_person_saturday": 900,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Aurora pool villa",
    "price_monday": 3000,
    "max_people_monday": 8,
    "price_tuesday": 3000,
    "max_people_tuesday": 8,
    "price_wednesday": 3000,
    "max_people_wednesday": 8,
    "price_thursday": 3000,
    "max_people_thursday": 8,
    "price_friday": 5000,
    "max_people_friday": 8,
    "price_saturday": 7000,
    "max_people_saturday": 8,
    "price_sunday": 3000,
    "max_people_sunday": 8,
    "far_sea": 2700,
    "bed_room": 3,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 375,
    "avg_price_per_person_tuesday": 375,
    "avg_price_per_person_wednesday": 375,
    "avg_price_per_person_thursday": 375,
    "avg_price_per_person_friday": 625,
    "avg_price_per_person_saturday": 875,
    "avg_price_per_person_sunday": 375
  },
  {
    "house_name": "Baba Beach Pool Villa",
    "price_monday": 5000,
    "max_people_monday": 10,
    "price_tuesday": 5000,
    "max_people_tuesday": 10,
    "price_wednesday": 5000,
    "max_people_wednesday": 10,
    "price_thursday": 5000,
    "max_people_thursday": 10,
    "price_friday": 7000,
    "max_people_friday": 10,
    "price_saturday": 12000,
    "max_people_saturday": 10,
    "price_sunday": 5000,
    "max_people_sunday": 10,
    "far_sea": 700,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 700,
    "avg_price_per_person_saturday": 1200,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Banana Tree Pool Villa",
    "price_monday": 5000,
    "max_people_monday": 12,
    "price_tuesday": 5000,
    "max_people_tuesday": 12,
    "price_wednesday": 5000,
    "max_people_wednesday": 12,
    "price_thursday": 5000,
    "max_people_thursday": 12,
    "price_friday": 7000,
    "max_people_friday": 12,
    "price_saturday": 11000,
    "max_people_saturday": 12,
    "price_sunday": 5000,
    "max_people_sunday": 12,
    "far_sea": 5000,
    "bed_room": 4,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 416.67,
    "avg_price_per_person_tuesday": 416.67,
    "avg_price_per_person_wednesday": 416.67,
    "avg_price_per_person_thursday": 416.67,
    "avg_price_per_person_friday": 583.33,
    "avg_price_per_person_saturday": 916.67,
    "avg_price_per_person_sunday": 416.67
  },
  {
    "house_name": "BB pool villa",
    "price_monday": 3000,
    "max_people_monday": 8,
    "price_tuesday": 3000,
    "max_people_tuesday": 8,
    "price_wednesday": 3000,
    "max_people_wednesday": 8,
    "price_thursday": 3000,
    "max_people_thursday": 8,
    "price_friday": 4000,
    "max_people_friday": 8,
    "price_saturday": 7000,
    "max_people_saturday": 8,
    "price_sunday": 3000,
    "max_people_sunday": 8,
    "far_sea": 1200,
    "bed_room": 2,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 375,
    "avg_price_per_person_tuesday": 375,
    "avg_price_per_person_wednesday": 375,
    "avg_price_per_person_thursday": 375,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 875,
    "avg_price_per_person_sunday": 375
  },
  {
    "house_name": "Black white pool villa",
    "price_monday": 4000,
    "max_people_monday": 8,
    "price_tuesday": 4000,
    "max_people_tuesday": 8,
    "price_wednesday": 4000,
    "max_people_wednesday": 8,
    "price_thursday": 4000,
    "max_people_thursday": 8,
    "price_friday": 5000,
    "max_people_friday": 8,
    "price_saturday": 8000,
    "max_people_saturday": 8,
    "price_sunday": 4000,
    "max_people_sunday": 8,
    "far_sea": 9000,
    "bed_room": 3,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 625,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "BLB pool villa",
    "price_monday": 30000,
    "max_people_monday": 48,
    "price_tuesday": 30000,
    "max_people_tuesday": 48,
    "price_wednesday": 30000,
    "max_people_wednesday": 48,
    "price_thursday": 30000,
    "max_people_thursday": 48,
    "price_friday": 34000,
    "max_people_friday": 48,
    "price_saturday": 34000,
    "max_people_saturday": 48,
    "price_sunday": 30000,
    "max_people_sunday": 48,
    "far_sea": 16000,
    "bed_room": 20,
    "toilet": 22,
    "total_floor": 1,
    "extra_fee_per_pet": 0,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 625,
    "avg_price_per_person_tuesday": 625,
    "avg_price_per_person_wednesday": 625,
    "avg_price_per_person_thursday": 625,
    "avg_price_per_person_friday": 708.33,
    "avg_price_per_person_saturday": 708.33,
    "avg_price_per_person_sunday": 625
  },
  {
    "house_name": "Camomile pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 6000,
    "max_people_friday": 10,
    "price_saturday": 10000,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 4300,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Castle pool villa",
    "price_monday": 5000,
    "max_people_monday": 10,
    "price_tuesday": 5000,
    "max_people_tuesday": 10,
    "price_wednesday": 5000,
    "max_people_wednesday": 10,
    "price_thursday": 5000,
    "max_people_thursday": 10,
    "price_friday": 7000,
    "max_people_friday": 10,
    "price_saturday": 12000,
    "max_people_saturday": 10,
    "price_sunday": 5000,
    "max_people_sunday": 10,
    "far_sea": 5600,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 700,
    "avg_price_per_person_saturday": 1200,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Cave Pool Villa",
    "price_monday": 10000,
    "max_people_monday": 25,
    "price_tuesday": 10000,
    "max_people_tuesday": 25,
    "price_wednesday": 10000,
    "max_people_wednesday": 25,
    "price_thursday": 10000,
    "max_people_thursday": 25,
    "price_friday": 10000,
    "max_people_friday": 25,
    "price_saturday": 20000,
    "max_people_saturday": 25,
    "price_sunday": 10000,
    "max_people_sunday": 25,
    "far_sea": 6100,
    "bed_room": 7,
    "toilet": 5,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 400,
    "avg_price_per_person_saturday": 800,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Cayla Pool Villa",
    "price_monday": 5000,
    "max_people_monday": 10,
    "price_tuesday": 5000,
    "max_people_tuesday": 10,
    "price_wednesday": 5000,
    "max_people_wednesday": 10,
    "price_thursday": 5000,
    "max_people_thursday": 10,
    "price_friday": 6000,
    "max_people_friday": 10,
    "price_saturday": 10000,
    "max_people_saturday": 10,
    "price_sunday": 5000,
    "max_people_sunday": 10,
    "far_sea": 8000,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Cherish house pool villa",
    "price_monday": 7000,
    "max_people_monday": 14,
    "price_tuesday": 7000,
    "max_people_tuesday": 14,
    "price_wednesday": 7000,
    "max_people_wednesday": 14,
    "price_thursday": 7000,
    "max_people_thursday": 14,
    "price_friday": 9000,
    "max_people_friday": 14,
    "price_saturday": 15000,
    "max_people_saturday": 14,
    "price_sunday": 7000,
    "max_people_sunday": 14,
    "far_sea": 4000,
    "bed_room": 5,
    "toilet": 6,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 642.86,
    "avg_price_per_person_saturday": 1071.43,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Chloe Pool Villa",
    "price_monday": 5000,
    "max_people_monday": 10,
    "price_tuesday": 5000,
    "max_people_tuesday": 10,
    "price_wednesday": 5000,
    "max_people_wednesday": 10,
    "price_thursday": 5000,
    "max_people_thursday": 10,
    "price_friday": 9000,
    "max_people_friday": 10,
    "price_saturday": 14000,
    "max_people_saturday": 10,
    "price_sunday": 6000,
    "max_people_sunday": 10,
    "far_sea": 7000,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 900,
    "avg_price_per_person_saturday": 1400,
    "avg_price_per_person_sunday": 600
  },
  {
    "house_name": "Claire Pool Villa",
    "price_monday": 8000,
    "max_people_monday": 12,
    "price_tuesday": 8000,
    "max_people_tuesday": 12,
    "price_wednesday": 8000,
    "max_people_wednesday": 12,
    "price_thursday": 8000,
    "max_people_thursday": 12,
    "price_friday": 9000,
    "max_people_friday": 12,
    "price_saturday": 15000,
    "max_people_saturday": 12,
    "price_sunday": 8000,
    "max_people_sunday": 12,
    "far_sea": 5400,
    "bed_room": 4,
    "toilet": 4,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 666.67,
    "avg_price_per_person_tuesday": 666.67,
    "avg_price_per_person_wednesday": 666.67,
    "avg_price_per_person_thursday": 666.67,
    "avg_price_per_person_friday": 750,
    "avg_price_per_person_saturday": 1250,
    "avg_price_per_person_sunday": 666.67
  },
  {
    "house_name": "Classy Pool Villa",
    "price_monday": 5000,
    "max_people_monday": 1,
    "price_tuesday": 5000,
    "max_people_tuesday": 1,
    "price_wednesday": 5000,
    "max_people_wednesday": 1,
    "price_thursday": 5000,
    "max_people_thursday": 1,
    "price_friday": 6000,
    "max_people_friday": 1,
    "price_saturday": 12000,
    "max_people_saturday": 1,
    "price_sunday": 5000,
    "max_people_sunday": 1,
    "far_sea": 6600,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 5000,
    "avg_price_per_person_tuesday": 5000,
    "avg_price_per_person_wednesday": 5000,
    "avg_price_per_person_thursday": 5000,
    "avg_price_per_person_friday": 6000,
    "avg_price_per_person_saturday": 12000,
    "avg_price_per_person_sunday": 5000
  },
  {
    "house_name": "Cloud Pool Villa",
    "price_monday": 7000,
    "max_people_monday": 16,
    "price_tuesday": 7000,
    "max_people_tuesday": 16,
    "price_wednesday": 7000,
    "max_people_wednesday": 16,
    "price_thursday": 7000,
    "max_people_thursday": 16,
    "price_friday": 8000,
    "max_people_friday": 16,
    "price_saturday": 15000,
    "max_people_saturday": 16,
    "price_sunday": 7000,
    "max_people_sunday": 16,
    "far_sea": 5000,
    "bed_room": 5,
    "toilet": 3,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 437.5,
    "avg_price_per_person_tuesday": 437.5,
    "avg_price_per_person_wednesday": 437.5,
    "avg_price_per_person_thursday": 437.5,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 937.5,
    "avg_price_per_person_sunday": 437.5
  },
  {
    "house_name": "Cocktail house pool villa",
    "price_monday": 4000,
    "max_people_monday": 12,
    "price_tuesday": 4000,
    "max_people_tuesday": 12,
    "price_wednesday": 4000,
    "max_people_wednesday": 12,
    "price_thursday": 4000,
    "max_people_thursday": 12,
    "price_friday": 6000,
    "max_people_friday": 12,
    "price_saturday": 9000,
    "max_people_saturday": 12,
    "price_sunday": 4000,
    "max_people_sunday": 12,
    "far_sea": 4300,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 333.33,
    "avg_price_per_person_tuesday": 333.33,
    "avg_price_per_person_wednesday": 333.33,
    "avg_price_per_person_thursday": 333.33,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 750,
    "avg_price_per_person_sunday": 333.33
  },
  {
    "house_name": "Crazy pool villa",
    "price_monday": 3000,
    "max_people_monday": 8,
    "price_tuesday": 3000,
    "max_people_tuesday": 8,
    "price_wednesday": 3000,
    "max_people_wednesday": 8,
    "price_thursday": 3000,
    "max_people_thursday": 8,
    "price_friday": 5000,
    "max_people_friday": 8,
    "price_saturday": 7000,
    "max_people_saturday": 8,
    "price_sunday": 3000,
    "max_people_sunday": 8,
    "far_sea": 3000,
    "bed_room": 3,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 375,
    "avg_price_per_person_tuesday": 375,
    "avg_price_per_person_wednesday": 375,
    "avg_price_per_person_thursday": 375,
    "avg_price_per_person_friday": 625,
    "avg_price_per_person_saturday": 875,
    "avg_price_per_person_sunday": 375
  },
  {
    "house_name": "Crop house pool villa",
    "price_monday": 6000,
    "max_people_monday": 20,
    "price_tuesday": 6000,
    "max_people_tuesday": 20,
    "price_wednesday": 6000,
    "max_people_wednesday": 20,
    "price_thursday": 6000,
    "max_people_thursday": 20,
    "price_friday": 8000,
    "max_people_friday": 20,
    "price_saturday": 12000,
    "max_people_saturday": 20,
    "price_sunday": 6000,
    "max_people_sunday": 20,
    "far_sea": 9300,
    "bed_room": 4,
    "toilet": 5,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 300,
    "avg_price_per_person_tuesday": 300,
    "avg_price_per_person_wednesday": 300,
    "avg_price_per_person_thursday": 300,
    "avg_price_per_person_friday": 400,
    "avg_price_per_person_saturday": 600,
    "avg_price_per_person_sunday": 300
  },
  {
    "house_name": "Disco pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 6000,
    "max_people_friday": 12,
    "price_saturday": 10000,
    "max_people_saturday": 12,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 4300,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 400,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 833.33,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Elysium pool villa",
    "price_monday": 7000,
    "max_people_monday": 15,
    "price_tuesday": 7000,
    "max_people_tuesday": 15,
    "price_wednesday": 7000,
    "max_people_wednesday": 15,
    "price_thursday": 7000,
    "max_people_thursday": 15,
    "price_friday": 9000,
    "max_people_friday": 15,
    "price_saturday": 15000,
    "max_people_saturday": 15,
    "price_sunday": 7000,
    "max_people_sunday": 15,
    "far_sea": 2700,
    "bed_room": 6,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 466.67,
    "avg_price_per_person_tuesday": 466.67,
    "avg_price_per_person_wednesday": 466.67,
    "avg_price_per_person_thursday": 466.67,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 466.67
  },
  {
    "house_name": "Emquatier Pool Viila",
    "price_monday": 14000,
    "max_people_monday": 28,
    "price_tuesday": 14000,
    "max_people_tuesday": 28,
    "price_wednesday": 14000,
    "max_people_wednesday": 28,
    "price_thursday": 14000,
    "max_people_thursday": 28,
    "price_friday": 20000,
    "max_people_friday": 28,
    "price_saturday": 30000,
    "max_people_saturday": 28,
    "price_sunday": 17000,
    "max_people_sunday": 28,
    "far_sea": 5500,
    "bed_room": 8,
    "toilet": 8,
    "total_floor": 3,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 714.29,
    "avg_price_per_person_saturday": 1071.43,
    "avg_price_per_person_sunday": 607.14
  },
  {
    "house_name": "Florimond pool villa",
    "price_monday": 7000,
    "max_people_monday": 20,
    "price_tuesday": 7000,
    "max_people_tuesday": 20,
    "price_wednesday": 7000,
    "max_people_wednesday": 20,
    "price_thursday": 7000,
    "max_people_thursday": 20,
    "price_friday": 9000,
    "max_people_friday": 20,
    "price_saturday": 15000,
    "max_people_saturday": 20,
    "price_sunday": 7000,
    "max_people_sunday": 20,
    "far_sea": 7200,
    "bed_room": 5,
    "toilet": 6,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 350,
    "avg_price_per_person_tuesday": 350,
    "avg_price_per_person_wednesday": 350,
    "avg_price_per_person_thursday": 350,
    "avg_price_per_person_friday": 450,
    "avg_price_per_person_saturday": 750,
    "avg_price_per_person_sunday": 350
  },
  {
    "house_name": "Graph Pool Villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 5000,
    "max_people_friday": 10,
    "price_saturday": 9000,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 5800,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 900,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Green view pool villa",
    "price_monday": 6000,
    "max_people_monday": 16,
    "price_tuesday": 6000,
    "max_people_tuesday": 16,
    "price_wednesday": 6000,
    "max_people_wednesday": 16,
    "price_thursday": 6000,
    "max_people_thursday": 16,
    "price_friday": 9000,
    "max_people_friday": 16,
    "price_saturday": 16000,
    "max_people_saturday": 16,
    "price_sunday": 6000,
    "max_people_sunday": 16,
    "far_sea": 11600,
    "bed_room": 6,
    "toilet": 5,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 375,
    "avg_price_per_person_tuesday": 375,
    "avg_price_per_person_wednesday": 375,
    "avg_price_per_person_thursday": 375,
    "avg_price_per_person_friday": 562.5,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 375
  },
  {
    "house_name": "Hampton Place Pool Villa",
    "price_monday": 8000,
    "max_people_monday": 15,
    "price_tuesday": 8000,
    "max_people_tuesday": 15,
    "price_wednesday": 8000,
    "max_people_wednesday": 15,
    "price_thursday": 8000,
    "max_people_thursday": 15,
    "price_friday": 9000,
    "max_people_friday": 15,
    "price_saturday": 15000,
    "max_people_saturday": 15,
    "price_sunday": 8000,
    "max_people_sunday": 15,
    "far_sea": 4800,
    "bed_room": 5,
    "toilet": 5,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 533.33,
    "avg_price_per_person_tuesday": 533.33,
    "avg_price_per_person_wednesday": 533.33,
    "avg_price_per_person_thursday": 533.33,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 533.33
  },
  {
    "house_name": "Heal pool villa",
    "price_monday": 6000,
    "max_people_monday": 12,
    "price_tuesday": 6000,
    "max_people_tuesday": 12,
    "price_wednesday": 6000,
    "max_people_wednesday": 12,
    "price_thursday": 6000,
    "max_people_thursday": 12,
    "price_friday": 7000,
    "max_people_friday": 12,
    "price_saturday": 12000,
    "max_people_saturday": 12,
    "price_sunday": 6000,
    "max_people_sunday": 12,
    "far_sea": 7200,
    "bed_room": 4,
    "toilet": 5,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 583.33,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Iloveu pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 5000,
    "max_people_friday": 10,
    "price_saturday": 9000,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 7200,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 900,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Justin Pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 6000,
    "max_people_friday": 10,
    "price_saturday": 9000,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 4300,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 900,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Kompletai 2 pool villa",
    "price_monday": 7000,
    "max_people_monday": 7,
    "price_tuesday": 7000,
    "max_people_tuesday": 7,
    "price_wednesday": 7000,
    "max_people_wednesday": 7,
    "price_thursday": 7000,
    "max_people_thursday": 7,
    "price_friday": 10000,
    "max_people_friday": 7,
    "price_saturday": 10000,
    "max_people_saturday": 7,
    "price_sunday": 7000,
    "max_people_sunday": 7,
    "far_sea": 8000,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 0,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 1000,
    "avg_price_per_person_tuesday": 1000,
    "avg_price_per_person_wednesday": 1000,
    "avg_price_per_person_thursday": 1000,
    "avg_price_per_person_friday": 1428.57,
    "avg_price_per_person_saturday": 1428.57,
    "avg_price_per_person_sunday": 1000
  },
  {
    "house_name": "Kompletia pool villa",
    "price_monday": 9000,
    "max_people_monday": 10,
    "price_tuesday": 9000,
    "max_people_tuesday": 10,
    "price_wednesday": 9000,
    "max_people_wednesday": 10,
    "price_thursday": 9000,
    "max_people_thursday": 10,
    "price_friday": 12000,
    "max_people_friday": 10,
    "price_saturday": 12000,
    "max_people_saturday": 10,
    "price_sunday": 9000,
    "max_people_sunday": 10,
    "far_sea": 8000,
    "bed_room": 4,
    "toilet": 6,
    "total_floor": 1,
    "extra_fee_per_pet": 0,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 900,
    "avg_price_per_person_tuesday": 900,
    "avg_price_per_person_wednesday": 900,
    "avg_price_per_person_thursday": 900,
    "avg_price_per_person_friday": 1200,
    "avg_price_per_person_saturday": 1200,
    "avg_price_per_person_sunday": 900
  },
  {
    "house_name": "La seal pool villa",
    "price_monday": 6000,
    "max_people_monday": 10,
    "price_tuesday": 6000,
    "max_people_tuesday": 10,
    "price_wednesday": 6000,
    "max_people_wednesday": 10,
    "price_thursday": 6000,
    "max_people_thursday": 10,
    "price_friday": 9000,
    "max_people_friday": 10,
    "price_saturday": 10000,
    "max_people_saturday": 10,
    "price_sunday": 6000,
    "max_people_sunday": 10,
    "far_sea": 11000,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 600,
    "avg_price_per_person_tuesday": 600,
    "avg_price_per_person_wednesday": 600,
    "avg_price_per_person_thursday": 600,
    "avg_price_per_person_friday": 900,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 600
  },
  {
    "house_name": "Maloon pool villa",
    "price_monday": 18000,
    "max_people_monday": 15,
    "price_tuesday": 18000,
    "max_people_tuesday": 15,
    "price_wednesday": 18000,
    "max_people_wednesday": 15,
    "price_thursday": 18000,
    "max_people_thursday": 15,
    "price_friday": 20000,
    "max_people_friday": 15,
    "price_saturday": 20000,
    "max_people_saturday": 15,
    "price_sunday": 18000,
    "max_people_sunday": 15,
    "far_sea": 100,
    "bed_room": 8,
    "toilet": 6,
    "total_floor": 2,
    "extra_fee_per_pet": 0,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 1200,
    "avg_price_per_person_tuesday": 1200,
    "avg_price_per_person_wednesday": 1200,
    "avg_price_per_person_thursday": 1200,
    "avg_price_per_person_friday": 1333.33,
    "avg_price_per_person_saturday": 1333.33,
    "avg_price_per_person_sunday": 1200
  },
  {
    "house_name": "Marin pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 6000,
    "max_people_friday": 10,
    "price_saturday": 10000,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 4400,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Milan pool villa",
    "price_monday": 6000,
    "max_people_monday": 10,
    "price_tuesday": 6000,
    "max_people_tuesday": 10,
    "price_wednesday": 6000,
    "max_people_wednesday": 10,
    "price_thursday": 6000,
    "max_people_thursday": 10,
    "price_friday": 10000,
    "max_people_friday": 10,
    "price_saturday": 10000,
    "max_people_saturday": 10,
    "price_sunday": 6000,
    "max_people_sunday": 10,
    "far_sea": 8800,
    "bed_room": 4,
    "toilet": 5,
    "total_floor": 2,
    "extra_fee_per_pet": 0,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 600,
    "avg_price_per_person_tuesday": 600,
    "avg_price_per_person_wednesday": 600,
    "avg_price_per_person_thursday": 600,
    "avg_price_per_person_friday": 1000,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 600
  },
  {
    "house_name": "Mina pool villa",
    "price_monday": 5000,
    "max_people_monday": 12,
    "price_tuesday": 5000,
    "max_people_tuesday": 12,
    "price_wednesday": 5000,
    "max_people_wednesday": 12,
    "price_thursday": 5000,
    "max_people_thursday": 12,
    "price_friday": 6000,
    "max_people_friday": 12,
    "price_saturday": 12000,
    "max_people_saturday": 12,
    "price_sunday": 5000,
    "max_people_sunday": 12,
    "far_sea": 7500,
    "bed_room": 4,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 0,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 416.67,
    "avg_price_per_person_tuesday": 416.67,
    "avg_price_per_person_wednesday": 416.67,
    "avg_price_per_person_thursday": 416.67,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 416.67
  },
  {
    "house_name": "Miss u1 pool villa",
    "price_monday": 4500,
    "max_people_monday": 12,
    "price_tuesday": 4500,
    "max_people_tuesday": 12,
    "price_wednesday": 4500,
    "max_people_wednesday": 12,
    "price_thursday": 4500,
    "max_people_thursday": 12,
    "price_friday": 6000,
    "max_people_friday": 12,
    "price_saturday": 10000,
    "max_people_saturday": 15,
    "price_sunday": 4500,
    "max_people_sunday": 12,
    "far_sea": 1700,
    "bed_room": 5,
    "toilet": 5,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 375,
    "avg_price_per_person_tuesday": 375,
    "avg_price_per_person_wednesday": 375,
    "avg_price_per_person_thursday": 375,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 666.67,
    "avg_price_per_person_sunday": 375
  },
  {
    "house_name": "Miss u2 pool villa",
    "price_monday": 2500,
    "max_people_monday": 6,
    "price_tuesday": 2500,
    "max_people_tuesday": 6,
    "price_wednesday": 2500,
    "max_people_wednesday": 6,
    "price_thursday": 2500,
    "max_people_thursday": 6,
    "price_friday": 3000,
    "max_people_friday": 6,
    "price_saturday": 5000,
    "max_people_saturday": 6,
    "price_sunday": 2500,
    "max_people_sunday": 6,
    "far_sea": 1700,
    "bed_room": 2,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 416.67,
    "avg_price_per_person_tuesday": 416.67,
    "avg_price_per_person_wednesday": 416.67,
    "avg_price_per_person_thursday": 416.67,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 833.33,
    "avg_price_per_person_sunday": 416.67
  },
  {
    "house_name": "Miss u3 pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 5000,
    "max_people_friday": 10,
    "price_saturday": 10000,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 1600,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Miss u4 pool villa",
    "price_monday": 7000,
    "max_people_monday": 10,
    "price_tuesday": 7000,
    "max_people_tuesday": 10,
    "price_wednesday": 7000,
    "max_people_wednesday": 10,
    "price_thursday": 7000,
    "max_people_thursday": 10,
    "price_friday": 9000,
    "max_people_friday": 10,
    "price_saturday": 12000,
    "max_people_saturday": 10,
    "price_sunday": 7000,
    "max_people_sunday": 10,
    "far_sea": 1400,
    "bed_room": 5,
    "toilet": 7,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 700,
    "avg_price_per_person_tuesday": 700,
    "avg_price_per_person_wednesday": 700,
    "avg_price_per_person_thursday": 700,
    "avg_price_per_person_friday": 900,
    "avg_price_per_person_saturday": 1200,
    "avg_price_per_person_sunday": 700
  },
  {
    "house_name": "Moana pool villa",
    "price_monday": 4000,
    "max_people_monday": 12,
    "price_tuesday": 4000,
    "max_people_tuesday": 12,
    "price_wednesday": 4000,
    "max_people_wednesday": 12,
    "price_thursday": 4000,
    "max_people_thursday": 12,
    "price_friday": 6000,
    "max_people_friday": 12,
    "price_saturday": 10000,
    "max_people_saturday": 12,
    "price_sunday": 4000,
    "max_people_sunday": 12,
    "far_sea": 4300,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 333.33,
    "avg_price_per_person_tuesday": 333.33,
    "avg_price_per_person_wednesday": 333.33,
    "avg_price_per_person_thursday": 333.33,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 833.33,
    "avg_price_per_person_sunday": 333.33
  },
  {
    "house_name": "Model Loft pool villa",
    "price_monday": 21000,
    "max_people_monday": 15,
    "price_tuesday": 21000,
    "max_people_tuesday": 15,
    "price_wednesday": 21000,
    "max_people_wednesday": 15,
    "price_thursday": 21000,
    "max_people_thursday": 15,
    "price_friday": 25000,
    "max_people_friday": 15,
    "price_saturday": 25000,
    "max_people_saturday": 15,
    "price_sunday": 21000,
    "max_people_sunday": 15,
    "far_sea": 2000,
    "bed_room": 6,
    "toilet": 7,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 1000,
    "avg_price_per_person_monday": 1400,
    "avg_price_per_person_tuesday": 1400,
    "avg_price_per_person_wednesday": 1400,
    "avg_price_per_person_thursday": 1400,
    "avg_price_per_person_friday": 1666.67,
    "avg_price_per_person_saturday": 1666.67,
    "avg_price_per_person_sunday": 1400
  },
  {
    "house_name": "Moon cave pool villa",
    "price_monday": 4000,
    "max_people_monday": 8,
    "price_tuesday": 4000,
    "max_people_tuesday": 8,
    "price_wednesday": 4000,
    "max_people_wednesday": 8,
    "price_thursday": 4000,
    "max_people_thursday": 8,
    "price_friday": 5000,
    "max_people_friday": 8,
    "price_saturday": 9000,
    "max_people_saturday": 8,
    "price_sunday": 4000,
    "max_people_sunday": 8,
    "far_sea": 3100,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 625,
    "avg_price_per_person_saturday": 1125,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Moon Roxy pool villa",
    "price_monday": 3000,
    "max_people_monday": 8,
    "price_tuesday": 3000,
    "max_people_tuesday": 8,
    "price_wednesday": 3000,
    "max_people_wednesday": 8,
    "price_thursday": 3000,
    "max_people_thursday": 8,
    "price_friday": 5000,
    "max_people_friday": 8,
    "price_saturday": 7000,
    "max_people_saturday": 8,
    "price_sunday": 3000,
    "max_people_sunday": 8,
    "far_sea": 2700,
    "bed_room": 3,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 375,
    "avg_price_per_person_tuesday": 375,
    "avg_price_per_person_wednesday": 375,
    "avg_price_per_person_thursday": 375,
    "avg_price_per_person_friday": 625,
    "avg_price_per_person_saturday": 875,
    "avg_price_per_person_sunday": 375
  },
  {
    "house_name": "Muse Pool Villa",
    "price_monday": 10000,
    "max_people_monday": 20,
    "price_tuesday": 10000,
    "max_people_tuesday": 20,
    "price_wednesday": 10000,
    "max_people_wednesday": 20,
    "price_thursday": 10000,
    "max_people_thursday": 20,
    "price_friday": 12000,
    "max_people_friday": 20,
    "price_saturday": 20000,
    "max_people_saturday": 20,
    "price_sunday": 10000,
    "max_people_sunday": 20,
    "far_sea": 7500,
    "bed_room": 7,
    "toilet": 6,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "New day pool villa",
    "price_monday": 5000,
    "max_people_monday": 14,
    "price_tuesday": 5000,
    "max_people_tuesday": 14,
    "price_wednesday": 5000,
    "max_people_wednesday": 14,
    "price_thursday": 5000,
    "max_people_thursday": 14,
    "price_friday": 6000,
    "max_people_friday": 14,
    "price_saturday": 10000,
    "max_people_saturday": 14,
    "price_sunday": 5000,
    "max_people_sunday": 14,
    "far_sea": 6500,
    "bed_room": 4,
    "toilet": 4,
    "total_floor": 2,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 357.14,
    "avg_price_per_person_tuesday": 357.14,
    "avg_price_per_person_wednesday": 357.14,
    "avg_price_per_person_thursday": 357.14,
    "avg_price_per_person_friday": 428.57,
    "avg_price_per_person_saturday": 714.29,
    "avg_price_per_person_sunday": 357.14
  },
  {
    "house_name": "Nifta pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 5000,
    "max_people_friday": 10,
    "price_saturday": 9000,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 7500,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 900,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "October pool villa",
    "price_monday": 6000,
    "max_people_monday": 12,
    "price_tuesday": 6000,
    "max_people_tuesday": 12,
    "price_wednesday": 6000,
    "max_people_wednesday": 12,
    "price_thursday": 6000,
    "max_people_thursday": 12,
    "price_friday": 9000,
    "max_people_friday": 12,
    "price_saturday": 13000,
    "max_people_saturday": 12,
    "price_sunday": 6000,
    "max_people_sunday": 12,
    "far_sea": 320,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 750,
    "avg_price_per_person_saturday": 1083.33,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Ongfong Grand Pool Villa",
    "price_monday": 12900,
    "max_people_monday": 14,
    "price_tuesday": 12900,
    "max_people_tuesday": 14,
    "price_wednesday": 12900,
    "max_people_wednesday": 14,
    "price_thursday": 12900,
    "max_people_thursday": 14,
    "price_friday": 13900,
    "max_people_friday": 14,
    "price_saturday": 13900,
    "max_people_saturday": 14,
    "price_sunday": 12900,
    "max_people_sunday": 14,
    "far_sea": 2000,
    "bed_room": 5,
    "toilet": 7,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 921.43,
    "avg_price_per_person_tuesday": 921.43,
    "avg_price_per_person_wednesday": 921.43,
    "avg_price_per_person_thursday": 921.43,
    "avg_price_per_person_friday": 992.86,
    "avg_price_per_person_saturday": 992.86,
    "avg_price_per_person_sunday": 921.43
  },
  {
    "house_name": "Ongfong Oasis Pool Villa",
    "price_monday": 11900,
    "max_people_monday": 14,
    "price_tuesday": 11900,
    "max_people_tuesday": 14,
    "price_wednesday": 11900,
    "max_people_wednesday": 14,
    "price_thursday": 11900,
    "max_people_thursday": 14,
    "price_friday": 13900,
    "max_people_friday": 14,
    "price_saturday": 13900,
    "max_people_saturday": 14,
    "price_sunday": 11900,
    "max_people_sunday": 14,
    "far_sea": 2000,
    "bed_room": 4,
    "toilet": 5,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 850,
    "avg_price_per_person_tuesday": 850,
    "avg_price_per_person_wednesday": 850,
    "avg_price_per_person_thursday": 850,
    "avg_price_per_person_friday": 992.86,
    "avg_price_per_person_saturday": 992.86,
    "avg_price_per_person_sunday": 850
  },
  {
    "house_name": "Ongfong Pool Villa",
    "price_monday": 7900,
    "max_people_monday": 10,
    "price_tuesday": 7900,
    "max_people_tuesday": 10,
    "price_wednesday": 7900,
    "max_people_wednesday": 10,
    "price_thursday": 7900,
    "max_people_thursday": 10,
    "price_friday": 11900,
    "max_people_friday": 10,
    "price_saturday": 11900,
    "max_people_saturday": 10,
    "price_sunday": 7900,
    "max_people_sunday": 10,
    "far_sea": 250,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 790,
    "avg_price_per_person_tuesday": 790,
    "avg_price_per_person_wednesday": 790,
    "avg_price_per_person_thursday": 790,
    "avg_price_per_person_friday": 1190,
    "avg_price_per_person_saturday": 1190,
    "avg_price_per_person_sunday": 790
  },
  {
    "house_name": "Phirom pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 5000,
    "max_people_friday": 10,
    "price_saturday": 8000,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 6300,
    "bed_room": 3,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 800,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Phirom2 pool villa",
    "price_monday": 3000,
    "max_people_monday": 8,
    "price_tuesday": 3000,
    "max_people_tuesday": 8,
    "price_wednesday": 3000,
    "max_people_wednesday": 8,
    "price_thursday": 3000,
    "max_people_thursday": 8,
    "price_friday": 4000,
    "max_people_friday": 8,
    "price_saturday": 8000,
    "max_people_saturday": 8,
    "price_sunday": 3000,
    "max_people_sunday": 8,
    "far_sea": 2700,
    "bed_room": 3,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 375,
    "avg_price_per_person_tuesday": 375,
    "avg_price_per_person_wednesday": 375,
    "avg_price_per_person_thursday": 375,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 375
  },
  {
    "house_name": "Phirom3 pool villa",
    "price_monday": 3000,
    "max_people_monday": 8,
    "price_tuesday": 3000,
    "max_people_tuesday": 8,
    "price_wednesday": 3000,
    "max_people_wednesday": 8,
    "price_thursday": 3000,
    "max_people_thursday": 8,
    "price_friday": 4000,
    "max_people_friday": 8,
    "price_saturday": 8000,
    "max_people_saturday": 8,
    "price_sunday": 3000,
    "max_people_sunday": 8,
    "far_sea": 3400,
    "bed_room": 3,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 375,
    "avg_price_per_person_tuesday": 375,
    "avg_price_per_person_wednesday": 375,
    "avg_price_per_person_thursday": 375,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 375
  },
  {
    "house_name": "Phirom4 pool villa",
    "price_monday": 4000,
    "max_people_monday": 8,
    "price_tuesday": 4000,
    "max_people_tuesday": 8,
    "price_wednesday": 4000,
    "max_people_wednesday": 8,
    "price_thursday": 4000,
    "max_people_thursday": 8,
    "price_friday": 5000,
    "max_people_friday": 8,
    "price_saturday": 8000,
    "max_people_saturday": 8,
    "price_sunday": 4000,
    "max_people_sunday": 8,
    "far_sea": 4500,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 625,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Phirom5 pool villa",
    "price_monday": 8000,
    "max_people_monday": 21,
    "price_tuesday": 8000,
    "max_people_tuesday": 21,
    "price_wednesday": 8000,
    "max_people_wednesday": 21,
    "price_thursday": 8000,
    "max_people_thursday": 21,
    "price_friday": 10000,
    "max_people_friday": 21,
    "price_saturday": 15000,
    "max_people_saturday": 21,
    "price_sunday": 8000,
    "max_people_sunday": 21,
    "far_sea": 3000,
    "bed_room": 7,
    "toilet": 7,
    "total_floor": 2,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 380.95,
    "avg_price_per_person_tuesday": 380.95,
    "avg_price_per_person_wednesday": 380.95,
    "avg_price_per_person_thursday": 380.95,
    "avg_price_per_person_friday": 476.19,
    "avg_price_per_person_saturday": 714.29,
    "avg_price_per_person_sunday": 380.95
  },
  {
    "house_name": "Phirom6 pool villa",
    "price_monday": 3000,
    "max_people_monday": 8,
    "price_tuesday": 3000,
    "max_people_tuesday": 8,
    "price_wednesday": 3000,
    "max_people_wednesday": 8,
    "price_thursday": 3000,
    "max_people_thursday": 8,
    "price_friday": 4000,
    "max_people_friday": 8,
    "price_saturday": 7000,
    "max_people_saturday": 8,
    "price_sunday": 3000,
    "max_people_sunday": 8,
    "far_sea": 3000,
    "bed_room": 3,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 375,
    "avg_price_per_person_tuesday": 375,
    "avg_price_per_person_wednesday": 375,
    "avg_price_per_person_thursday": 375,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 875,
    "avg_price_per_person_sunday": 375
  },
  {
    "house_name": "Phirom7 pool villa",
    "price_monday": 5000,
    "max_people_monday": 12,
    "price_tuesday": 5000,
    "max_people_tuesday": 12,
    "price_wednesday": 5000,
    "max_people_wednesday": 12,
    "price_thursday": 5000,
    "max_people_thursday": 12,
    "price_friday": 8900,
    "max_people_friday": 12,
    "price_saturday": 10000,
    "max_people_saturday": 12,
    "price_sunday": 5000,
    "max_people_sunday": 12,
    "far_sea": 2700,
    "bed_room": 4,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 416.67,
    "avg_price_per_person_tuesday": 416.67,
    "avg_price_per_person_wednesday": 416.67,
    "avg_price_per_person_thursday": 416.67,
    "avg_price_per_person_friday": 741.67,
    "avg_price_per_person_saturday": 833.33,
    "avg_price_per_person_sunday": 416.67
  },
  {
    "house_name": "Phirom8 pool villa",
    "price_monday": 3000,
    "max_people_monday": 8,
    "price_tuesday": 3000,
    "max_people_tuesday": 8,
    "price_wednesday": 3000,
    "max_people_wednesday": 8,
    "price_thursday": 3000,
    "max_people_thursday": 8,
    "price_friday": 4000,
    "max_people_friday": 8,
    "price_saturday": 7000,
    "max_people_saturday": 8,
    "price_sunday": 3000,
    "max_people_sunday": 8,
    "far_sea": 3300,
    "bed_room": 3,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 375,
    "avg_price_per_person_tuesday": 375,
    "avg_price_per_person_wednesday": 375,
    "avg_price_per_person_thursday": 375,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 875,
    "avg_price_per_person_sunday": 375
  },
  {
    "house_name": "Ralph Pool Villa",
    "price_monday": 11000,
    "max_people_monday": 20,
    "price_tuesday": 11000,
    "max_people_tuesday": 20,
    "price_wednesday": 11000,
    "max_people_wednesday": 20,
    "price_thursday": 11000,
    "max_people_thursday": 20,
    "price_friday": 12000,
    "max_people_friday": 20,
    "price_saturday": 22000,
    "max_people_saturday": 20,
    "price_sunday": 11000,
    "max_people_sunday": 20,
    "far_sea": 6000,
    "bed_room": 7,
    "toilet": 6,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 550,
    "avg_price_per_person_tuesday": 550,
    "avg_price_per_person_wednesday": 550,
    "avg_price_per_person_thursday": 550,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1100,
    "avg_price_per_person_sunday": 550
  },
  {
    "house_name": "S&P pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 5000,
    "max_people_friday": 12,
    "price_saturday": 10000,
    "max_people_saturday": 12,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 5100,
    "bed_room": 4,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 416.67,
    "avg_price_per_person_saturday": 833.33,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Scarlet pool villa",
    "price_monday": 3000,
    "max_people_monday": 12,
    "price_tuesday": 3000,
    "max_people_tuesday": 12,
    "price_wednesday": 3000,
    "max_people_wednesday": 12,
    "price_thursday": 3000,
    "max_people_thursday": 12,
    "price_friday": 5000,
    "max_people_friday": 12,
    "price_saturday": 8000,
    "max_people_saturday": 12,
    "price_sunday": 3000,
    "max_people_sunday": 12,
    "far_sea": 4300,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 250,
    "avg_price_per_person_tuesday": 250,
    "avg_price_per_person_wednesday": 250,
    "avg_price_per_person_thursday": 250,
    "avg_price_per_person_friday": 416.67,
    "avg_price_per_person_saturday": 666.67,
    "avg_price_per_person_sunday": 250
  },
  {
    "house_name": "Sea Velora pool villa",
    "price_monday": 9000,
    "max_people_monday": 16,
    "price_tuesday": 9000,
    "max_people_tuesday": 16,
    "price_wednesday": 9000,
    "max_people_wednesday": 16,
    "price_thursday": 9000,
    "max_people_thursday": 16,
    "price_friday": 13000,
    "max_people_friday": 16,
    "price_saturday": 18000,
    "max_people_saturday": 16,
    "price_sunday": 9000,
    "max_people_sunday": 16,
    "far_sea": 210,
    "bed_room": 6,
    "toilet": 5,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 562.5,
    "avg_price_per_person_tuesday": 562.5,
    "avg_price_per_person_wednesday": 562.5,
    "avg_price_per_person_thursday": 562.5,
    "avg_price_per_person_friday": 812.5,
    "avg_price_per_person_saturday": 1125,
    "avg_price_per_person_sunday": 562.5
  },
  {
    "house_name": "Seattle pool villa",
    "price_monday": 10000,
    "max_people_monday": 16,
    "price_tuesday": 10000,
    "max_people_tuesday": 16,
    "price_wednesday": 10000,
    "max_people_wednesday": 16,
    "price_thursday": 10000,
    "max_people_thursday": 16,
    "price_friday": 12000,
    "max_people_friday": 16,
    "price_saturday": 17000,
    "max_people_saturday": 16,
    "price_sunday": 10000,
    "max_people_sunday": 16,
    "far_sea": 8500,
    "bed_room": 4,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 625,
    "avg_price_per_person_tuesday": 625,
    "avg_price_per_person_wednesday": 625,
    "avg_price_per_person_thursday": 625,
    "avg_price_per_person_friday": 750,
    "avg_price_per_person_saturday": 1062.5,
    "avg_price_per_person_sunday": 625
  },
  {
    "house_name": "Shawty pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 6000,
    "max_people_friday": 10,
    "price_saturday": 8500,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 4300,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 850,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "Silver Hill Pool Villa",
    "price_monday": 7000,
    "max_people_monday": 12,
    "price_tuesday": 7000,
    "max_people_tuesday": 12,
    "price_wednesday": 7000,
    "max_people_wednesday": 12,
    "price_thursday": 7000,
    "max_people_thursday": 12,
    "price_friday": 7000,
    "max_people_friday": 12,
    "price_saturday": 14000,
    "max_people_saturday": 12,
    "price_sunday": 7000,
    "max_people_sunday": 12,
    "far_sea": 5000,
    "bed_room": 4,
    "toilet": 4,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 583.33,
    "avg_price_per_person_tuesday": 583.33,
    "avg_price_per_person_wednesday": 583.33,
    "avg_price_per_person_thursday": 583.33,
    "avg_price_per_person_friday": 583.33,
    "avg_price_per_person_saturday": 1166.67,
    "avg_price_per_person_sunday": 583.33
  },
  {
    "house_name": "Siya pool villa",
    "price_monday": 7000,
    "max_people_monday": 12,
    "price_tuesday": 7000,
    "max_people_tuesday": 12,
    "price_wednesday": 7000,
    "max_people_wednesday": 12,
    "price_thursday": 7000,
    "max_people_thursday": 12,
    "price_friday": 8000,
    "max_people_friday": 12,
    "price_saturday": 16000,
    "max_people_saturday": 12,
    "price_sunday": 7000,
    "max_people_sunday": 12,
    "far_sea": 3400,
    "bed_room": 5,
    "toilet": 5,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 583.33,
    "avg_price_per_person_tuesday": 583.33,
    "avg_price_per_person_wednesday": 583.33,
    "avg_price_per_person_thursday": 583.33,
    "avg_price_per_person_friday": 666.67,
    "avg_price_per_person_saturday": 1333.33,
    "avg_price_per_person_sunday": 583.33
  },
  {
    "house_name": "Sun&zone 2 pool villa",
    "price_monday": 11000,
    "max_people_monday": 18,
    "price_tuesday": 11000,
    "max_people_tuesday": 18,
    "price_wednesday": 11000,
    "max_people_wednesday": 18,
    "price_thursday": 11000,
    "max_people_thursday": 18,
    "price_friday": 13000,
    "max_people_friday": 18,
    "price_saturday": 18000,
    "max_people_saturday": 18,
    "price_sunday": 13000,
    "max_people_sunday": 18,
    "far_sea": 7000,
    "bed_room": 5,
    "toilet": 6,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 611.11,
    "avg_price_per_person_tuesday": 611.11,
    "avg_price_per_person_wednesday": 611.11,
    "avg_price_per_person_thursday": 611.11,
    "avg_price_per_person_friday": 722.22,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 722.22
  },
  {
    "house_name": "Sun&Zone1 Pool villa",
    "price_monday": 7000,
    "max_people_monday": 12,
    "price_tuesday": 7000,
    "max_people_tuesday": 12,
    "price_wednesday": 7000,
    "max_people_wednesday": 12,
    "price_thursday": 7000,
    "max_people_thursday": 12,
    "price_friday": 8000,
    "max_people_friday": 12,
    "price_saturday": 12000,
    "max_people_saturday": 12,
    "price_sunday": 8000,
    "max_people_sunday": 12,
    "far_sea": 7000,
    "bed_room": 4,
    "toilet": 5,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 583.33,
    "avg_price_per_person_tuesday": 583.33,
    "avg_price_per_person_wednesday": 583.33,
    "avg_price_per_person_thursday": 583.33,
    "avg_price_per_person_friday": 666.67,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 666.67
  },
  {
    "house_name": "Sunshine 2 pool villa",
    "price_monday": 3500,
    "max_people_monday": 10,
    "price_tuesday": 3500,
    "max_people_tuesday": 10,
    "price_wednesday": 3500,
    "max_people_wednesday": 10,
    "price_thursday": 3500,
    "max_people_thursday": 10,
    "price_friday": 4500,
    "max_people_friday": 10,
    "price_saturday": 7500,
    "max_people_saturday": 10,
    "price_sunday": 3500,
    "max_people_sunday": 10,
    "far_sea": 12000,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 350,
    "avg_price_per_person_tuesday": 350,
    "avg_price_per_person_wednesday": 350,
    "avg_price_per_person_thursday": 350,
    "avg_price_per_person_friday": 450,
    "avg_price_per_person_saturday": 750,
    "avg_price_per_person_sunday": 350
  },
  {
    "house_name": "Sunshine 3 pool villa",
    "price_monday": 5000,
    "max_people_monday": 10,
    "price_tuesday": 5000,
    "max_people_tuesday": 10,
    "price_wednesday": 5000,
    "max_people_wednesday": 10,
    "price_thursday": 5000,
    "max_people_thursday": 10,
    "price_friday": 6000,
    "max_people_friday": 10,
    "price_saturday": 9000,
    "max_people_saturday": 10,
    "price_sunday": 5000,
    "max_people_sunday": 10,
    "far_sea": 5600,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 900,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Sunshine1 pool villa",
    "price_monday": 3500,
    "max_people_monday": 10,
    "price_tuesday": 3500,
    "max_people_tuesday": 10,
    "price_wednesday": 3500,
    "max_people_wednesday": 10,
    "price_thursday": 3500,
    "max_people_thursday": 10,
    "price_friday": 4500,
    "max_people_friday": 10,
    "price_saturday": 7500,
    "max_people_saturday": 10,
    "price_sunday": 3500,
    "max_people_sunday": 10,
    "far_sea": 12200,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 350,
    "avg_price_per_person_tuesday": 350,
    "avg_price_per_person_wednesday": 350,
    "avg_price_per_person_thursday": 350,
    "avg_price_per_person_friday": 450,
    "avg_price_per_person_saturday": 750,
    "avg_price_per_person_sunday": 350
  },
  {
    "house_name": "Teddy house pool villa",
    "price_monday": 3500,
    "max_people_monday": 10,
    "price_tuesday": 3500,
    "max_people_tuesday": 10,
    "price_wednesday": 3500,
    "max_people_wednesday": 10,
    "price_thursday": 3500,
    "max_people_thursday": 10,
    "price_friday": 5500,
    "max_people_friday": 10,
    "price_saturday": 8500,
    "max_people_saturday": 10,
    "price_sunday": 5500,
    "max_people_sunday": 10,
    "far_sea": 6400,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 350,
    "avg_price_per_person_tuesday": 350,
    "avg_price_per_person_wednesday": 350,
    "avg_price_per_person_thursday": 350,
    "avg_price_per_person_friday": 550,
    "avg_price_per_person_saturday": 850,
    "avg_price_per_person_sunday": 550
  },
  {
    "house_name": "The H pool villa",
    "price_monday": 3500,
    "max_people_monday": 10,
    "price_tuesday": 3500,
    "max_people_tuesday": 10,
    "price_wednesday": 3500,
    "max_people_wednesday": 10,
    "price_thursday": 3500,
    "max_people_thursday": 10,
    "price_friday": 4000,
    "max_people_friday": 10,
    "price_saturday": 8000,
    "max_people_saturday": 10,
    "price_sunday": 3500,
    "max_people_sunday": 10,
    "far_sea": 8000,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 350,
    "avg_price_per_person_tuesday": 350,
    "avg_price_per_person_wednesday": 350,
    "avg_price_per_person_thursday": 350,
    "avg_price_per_person_friday": 400,
    "avg_price_per_person_saturday": 800,
    "avg_price_per_person_sunday": 350
  },
  {
    "house_name": "The H2 pool villa",
    "price_monday": 7000,
    "max_people_monday": 16,
    "price_tuesday": 7000,
    "max_people_tuesday": 16,
    "price_wednesday": 7000,
    "max_people_wednesday": 16,
    "price_thursday": 7000,
    "max_people_thursday": 16,
    "price_friday": 8000,
    "max_people_friday": 16,
    "price_saturday": 11000,
    "max_people_saturday": 16,
    "price_sunday": 7000,
    "max_people_sunday": 16,
    "far_sea": 8000,
    "bed_room": 5,
    "toilet": 4,
    "total_floor": 2,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 437.5,
    "avg_price_per_person_tuesday": 437.5,
    "avg_price_per_person_wednesday": 437.5,
    "avg_price_per_person_thursday": 437.5,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 687.5,
    "avg_price_per_person_sunday": 437.5
  },
  {
    "house_name": "The Moment Pool Villa",
    "price_monday": 13000,
    "max_people_monday": 20,
    "price_tuesday": 13000,
    "max_people_tuesday": 20,
    "price_wednesday": 13000,
    "max_people_wednesday": 20,
    "price_thursday": 13000,
    "max_people_thursday": 20,
    "price_friday": 16000,
    "max_people_friday": 20,
    "price_saturday": 25000,
    "max_people_saturday": 20,
    "price_sunday": 13000,
    "max_people_sunday": 20,
    "far_sea": 4000,
    "bed_room": 8,
    "toilet": 8,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 650,
    "avg_price_per_person_tuesday": 650,
    "avg_price_per_person_wednesday": 650,
    "avg_price_per_person_thursday": 650,
    "avg_price_per_person_friday": 800,
    "avg_price_per_person_saturday": 1250,
    "avg_price_per_person_sunday": 650
  },
  {
    "house_name": "Tropica pool villa",
    "price_monday": 4000,
    "max_people_monday": 15,
    "price_tuesday": 4000,
    "max_people_tuesday": 15,
    "price_wednesday": 4000,
    "max_people_wednesday": 15,
    "price_thursday": 4000,
    "max_people_thursday": 15,
    "price_friday": 6000,
    "max_people_friday": 15,
    "price_saturday": 11000,
    "max_people_saturday": 15,
    "price_sunday": 4000,
    "max_people_sunday": 15,
    "far_sea": 7400,
    "bed_room": 5,
    "toilet": 5,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 266.67,
    "avg_price_per_person_tuesday": 266.67,
    "avg_price_per_person_wednesday": 266.67,
    "avg_price_per_person_thursday": 266.67,
    "avg_price_per_person_friday": 400,
    "avg_price_per_person_saturday": 733.33,
    "avg_price_per_person_sunday": 266.67
  },
  {
    "house_name": "Umbrella Pool Villa",
    "price_monday": 5000,
    "max_people_monday": 10,
    "price_tuesday": 5000,
    "max_people_tuesday": 10,
    "price_wednesday": 5000,
    "max_people_wednesday": 10,
    "price_thursday": 5000,
    "max_people_thursday": 10,
    "price_friday": 6000,
    "max_people_friday": 10,
    "price_saturday": 11000,
    "max_people_saturday": 10,
    "price_sunday": 5000,
    "max_people_sunday": 10,
    "far_sea": 4200,
    "bed_room": 4,
    "toilet": 2,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1100,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Villa de moon",
    "price_monday": 12000,
    "max_people_monday": 16,
    "price_tuesday": 12000,
    "max_people_tuesday": 16,
    "price_wednesday": 12000,
    "max_people_wednesday": 16,
    "price_thursday": 12000,
    "max_people_thursday": 16,
    "price_friday": 15000,
    "max_people_friday": 18,
    "price_saturday": 23000,
    "max_people_saturday": 18,
    "price_sunday": 12000,
    "max_people_sunday": 16,
    "far_sea": 7000,
    "bed_room": 7,
    "toilet": 8,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 750,
    "avg_price_per_person_tuesday": 750,
    "avg_price_per_person_wednesday": 750,
    "avg_price_per_person_thursday": 750,
    "avg_price_per_person_friday": 833.33,
    "avg_price_per_person_saturday": 1277.78,
    "avg_price_per_person_sunday": 750
  },
  {
    "house_name": "Villa whale",
    "price_monday": 3000,
    "max_people_monday": 10,
    "price_tuesday": 3000,
    "max_people_tuesday": 10,
    "price_wednesday": 3000,
    "max_people_wednesday": 10,
    "price_thursday": 3000,
    "max_people_thursday": 10,
    "price_friday": 5000,
    "max_people_friday": 10,
    "price_saturday": 8000,
    "max_people_saturday": 10,
    "price_sunday": 3000,
    "max_people_sunday": 10,
    "far_sea": 4300,
    "bed_room": 3,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 300,
    "avg_price_per_person_tuesday": 300,
    "avg_price_per_person_wednesday": 300,
    "avg_price_per_person_thursday": 300,
    "avg_price_per_person_friday": 500,
    "avg_price_per_person_saturday": 800,
    "avg_price_per_person_sunday": 300
  },
  {
    "house_name": "Walter's House",
    "price_monday": 9000,
    "max_people_monday": 16,
    "price_tuesday": 9000,
    "max_people_tuesday": 16,
    "price_wednesday": 9000,
    "max_people_wednesday": 16,
    "price_thursday": 9000,
    "max_people_thursday": 16,
    "price_friday": 10000,
    "max_people_friday": 16,
    "price_saturday": 16000,
    "max_people_saturday": 16,
    "price_sunday": 9000,
    "max_people_sunday": 16,
    "far_sea": 5600,
    "bed_room": 6,
    "toilet": 5,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 562.5,
    "avg_price_per_person_tuesday": 562.5,
    "avg_price_per_person_wednesday": 562.5,
    "avg_price_per_person_thursday": 562.5,
    "avg_price_per_person_friday": 625,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 562.5
  },
  {
    "house_name": "Wasan 1 pool Villa",
    "price_monday": 5000,
    "max_people_monday": 10,
    "price_tuesday": 5000,
    "max_people_tuesday": 10,
    "price_wednesday": 5000,
    "max_people_wednesday": 10,
    "price_thursday": 5000,
    "max_people_thursday": 10,
    "price_friday": 6000,
    "max_people_friday": 10,
    "price_saturday": 12000,
    "max_people_saturday": 10,
    "price_sunday": 5000,
    "max_people_sunday": 10,
    "far_sea": 7500,
    "bed_room": 4,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1200,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Wasan2 pool Villa",
    "price_monday": 6000,
    "max_people_monday": 12,
    "price_tuesday": 6000,
    "max_people_tuesday": 12,
    "price_wednesday": 6000,
    "max_people_wednesday": 12,
    "price_thursday": 6000,
    "max_people_thursday": 12,
    "price_friday": 7000,
    "max_people_friday": 12,
    "price_saturday": 12000,
    "max_people_saturday": 12,
    "price_sunday": 6000,
    "max_people_sunday": 12,
    "far_sea": 7300,
    "bed_room": 4,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 583.33,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Wasan3 pool Villa",
    "price_monday": 6000,
    "max_people_monday": 12,
    "price_tuesday": 6000,
    "max_people_tuesday": 12,
    "price_wednesday": 6000,
    "max_people_wednesday": 12,
    "price_thursday": 6000,
    "max_people_thursday": 12,
    "price_friday": 7000,
    "max_people_friday": 12,
    "price_saturday": 12000,
    "max_people_saturday": 12,
    "price_sunday": 6000,
    "max_people_sunday": 12,
    "far_sea": 7200,
    "bed_room": 4,
    "toilet": 4,
    "total_floor": 1,
    "extra_fee_per_pet": 300,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 583.33,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Wealthy house pool villa",
    "price_monday": 4000,
    "max_people_monday": 10,
    "price_tuesday": 4000,
    "max_people_tuesday": 10,
    "price_wednesday": 4000,
    "max_people_wednesday": 10,
    "price_thursday": 4000,
    "max_people_thursday": 10,
    "price_friday": 7000,
    "max_people_friday": 10,
    "price_saturday": 11000,
    "max_people_saturday": 10,
    "price_sunday": 4000,
    "max_people_sunday": 10,
    "far_sea": 2600,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 400,
    "avg_price_per_person_tuesday": 400,
    "avg_price_per_person_wednesday": 400,
    "avg_price_per_person_thursday": 400,
    "avg_price_per_person_friday": 700,
    "avg_price_per_person_saturday": 1100,
    "avg_price_per_person_sunday": 400
  },
  {
    "house_name": "White Chocolate Pool Villa",
    "price_monday": 7000,
    "max_people_monday": 14,
    "price_tuesday": 7000,
    "max_people_tuesday": 14,
    "price_wednesday": 7000,
    "max_people_wednesday": 14,
    "price_thursday": 7000,
    "max_people_thursday": 14,
    "price_friday": 9000,
    "max_people_friday": 14,
    "price_saturday": 15000,
    "max_people_saturday": 14,
    "price_sunday": 7000,
    "max_people_sunday": 14,
    "far_sea": 4500,
    "bed_room": 5,
    "toilet": 4,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 642.86,
    "avg_price_per_person_saturday": 1071.43,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "White House Pool Villa",
    "price_monday": 5000,
    "max_people_monday": 10,
    "price_tuesday": 5000,
    "max_people_tuesday": 10,
    "price_wednesday": 5000,
    "max_people_wednesday": 10,
    "price_thursday": 5000,
    "max_people_thursday": 10,
    "price_friday": 6000,
    "max_people_friday": 10,
    "price_saturday": 10000,
    "max_people_saturday": 10,
    "price_sunday": 5000,
    "max_people_sunday": 10,
    "far_sea": 450,
    "bed_room": 3,
    "toilet": 3,
    "total_floor": 2,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 300,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 600,
    "avg_price_per_person_saturday": 1000,
    "avg_price_per_person_sunday": 500
  },
  {
    "house_name": "Wind Hill House",
    "price_monday": 8000,
    "max_people_monday": 16,
    "price_tuesday": 8000,
    "max_people_tuesday": 16,
    "price_wednesday": 8000,
    "max_people_wednesday": 16,
    "price_thursday": 8000,
    "max_people_thursday": 16,
    "price_friday": 9000,
    "max_people_friday": 16,
    "price_saturday": 15000,
    "max_people_saturday": 16,
    "price_sunday": 8000,
    "max_people_sunday": 16,
    "far_sea": 5500,
    "bed_room": 5,
    "toilet": 6,
    "total_floor": 1,
    "extra_fee_per_pet": 500,
    "extra_fee_per_person": 500,
    "avg_price_per_person_monday": 500,
    "avg_price_per_person_tuesday": 500,
    "avg_price_per_person_wednesday": 500,
    "avg_price_per_person_thursday": 500,
    "avg_price_per_person_friday": 562.5,
    "avg_price_per_person_saturday": 937.5,
    "avg_price_per_person_sunday": 500
  }
];
